export const mockSaltIngredient = [
  {
    strMeal: 'Apam balik',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/adxcbq1619787919.jpg',
    idMeal: '53049',
  },
  {
    strMeal: 'Baingan Bharta',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg',
    idMeal: '52807',
  },
  {
    strMeal: 'BeaverTails',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/ryppsv1511815505.jpg',
    idMeal: '52928',
  },
  {
    strMeal: 'Beef Brisket Pot Roast',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/ursuup1487348423.jpg',
    idMeal: '52812',
  },
  {
    strMeal: 'Beef Lo Mein',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/1529444830.jpg',
    idMeal: '52952',
  },
  {
    strMeal: 'Bitterballen (Dutch meatballs)',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/lhqev81565090111.jpg',
    idMeal: '52979',
  },
  {
    strMeal: 'Breakfast Potatoes',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/1550441882.jpg',
    idMeal: '52965',
  },
  {
    strMeal: 'Burek',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg',
    idMeal: '53060',
  },
  {
    strMeal: 'Carrot Cake',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/vrspxv1511722107.jpg',
    idMeal: '52897',
  },
  {
    strMeal: 'Cevapi Sausages',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/vc08jn1628769553.jpg',
    idMeal: '53055',
  },
  {
    strMeal: 'Chakchouka ',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/gpz67p1560458984.jpg',
    idMeal: '52969',
  },
  {
    strMeal: 'Chelsea Buns',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/vqpwrv1511723001.jpg',
    idMeal: '52898',
  },
  {
    strMeal: 'Chick-Fil-A Sandwich',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/sbx7n71587673021.jpg',
    idMeal: '53016',
  },
  {
    strMeal: 'Chicken Alfredo Primavera',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg',
    idMeal: '52796',
  },
  {
    strMeal: 'Chicken Congee',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/1529446352.jpg',
    idMeal: '52956',
  }];

export const mockSpicyArrabiata = {
  meals: [{
    idMeal: '52771',
    strMeal: 'Spicy Arrabiata Penne',
    strDrinkAlternate: null,
    strCategory: 'Vegetarian',
    strArea: 'Italian',
    strInstructions: 'Bring a large pot of water to a boil.',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg',
    strTags: 'Pasta,Curry',
    strYoutube: 'https://www.youtube.com/watch?v=1IszT_guI08',
    strIngredient1: 'penne rigate',
    strIngredient2: 'olive oil',
    strIngredient3: 'garlic',
    strIngredient4: 'chopped tomatoes',
    strIngredient5: 'red chile flakes',
    strIngredient6: 'italian seasoning',
    strIngredient7: 'basil',
    strIngredient8: 'Parmigiano-Reggiano',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: null,
    strIngredient17: null,
    strIngredient18: null,
    strIngredient19: null,
    strIngredient20: null,
    strMeasure1: '1 pound',
    strMeasure2: '1/4 cup',
    strMeasure3: '3 cloves',
    strMeasure4: '1 tin ',
    strMeasure5: '1/2 teaspoon',
    strMeasure6: '1/2 teaspoon',
    strMeasure7: '6 leaves',
    strMeasure8: 'spinkling',
    strMeasure9: '',
    strMeasure10: '',
    strMeasure11: '',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: null,
    strMeasure17: null,
    strMeasure18: null,
    strMeasure19: null,
    strMeasure20: null,
    strSource: null,
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  }],
};

export const mockAquamarine = {
  drinks: [
    {
      idDrink: '178319',
      strDrink: 'Aquamarine',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Martini Glass',
      strInstructions: 'Shake well in a shaker with ice.\r\nStrain in a martini glass.',
      strInstructionsES: 'Agite bien en una coctelera con hielo. Cuela en una copa de Martini.',
      strInstructionsDE: null,
      strInstructionsFR: null,
      strInstructionsIT: 'Shakerare bene in uno shaker con ghiaccio.\r\nFiltrare in una coppetta Martini.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/zvsre31572902738.jpg',
      strIngredient1: 'Hpnotiq',
      strIngredient2: 'Pineapple Juice',
      strIngredient3: 'Banana Liqueur',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz',
      strMeasure2: '1 oz',
      strMeasure3: '1 oz',
      strMeasure4: '',
      strMeasure5: '',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: null,
    },
  ],
};
