import React from 'react';
import { screen, waitForElementToBeRemoved } from '@testing-library/react';
import RecipeDetails from '../pages/RecipeDetails';
import renderWithRouter from './renderWithRouter';

const mockFoodData = {
  "meals": [
    {
      "idMeal": "52904",
      "strMeal": "Beef Bourguignon",
      "strDrinkAlternate": null,
      "strCategory": "Beef",
      "strArea": "French",
      "strInstructions": "Heat a large casserole pan and add 1 tbsp goose fat. Season the beef and fry until golden brown, about 3-5 mins, then turn over and fry the other side until the meat is browned all over, adding more fat if necessary. Do this in 2-3 batches, transferring the meat to a colander set over a bowl when browned.\r\nIn the same pan, fry the bacon, shallots or pearl onions, mushrooms, garlic and bouquet garni until lightly browned. Mix in the tomato purée and cook for a few mins, stirring into the mixture. This enriches the bourguignon and makes a great base for the stew. Then return the beef and any drained juices to the pan and stir through.\r\nPour over the wine and about 100ml water so the meat bobs up from the liquid, but isn’t completely covered. Bring to the boil and use a spoon to scrape the caramelised cooking juices from the bottom of the pan – this will give the stew more flavour.\r\nHeat oven to 150C/fan 130C/gas 2. Make a cartouche: tear off a square of foil slightly larger than the casserole, arrange it in the pan so it covers the top of the stew and trim away any excess foil. Then cook for 3 hrs. If the sauce looks watery, remove the beef and veg with a slotted spoon, and set aside. Cook the sauce over a high heat for a few mins until the sauce has thickened a little, then return the beef and vegetables to the pan.\r\nTo make the celeriac mash, peel the celeriac and cut into cubes. Heat the olive oil in a large frying pan. Tip in the celeriac and fry for 5 mins until it turns golden. Season well with salt and pepper. Stir in the rosemary, thyme, bay and cardamom pods, then pour over 200ml water, enough to nearly cover the celeriac. Turn the heat to low, partially cover the pan and leave to simmer for 25-30 mins.\r\nAfter 25-30 mins, the celeriac should be soft and most of the water will have evaporated. Drain away any remaining water, then remove the herb sprigs, bay and cardamom pods. Lightly crush with a potato masher, then finish with a glug of olive oil and season to taste. Spoon the beef bourguignon into serving bowls and place a large spoonful of the celeriac mash on top. Garnish with one of the bay leaves, if you like.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/vtqxtu1511784197.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=SQnr4Z-7rok",
      "strIngredient1": "Goose Fat",
      "strIngredient2": "Beef Shin",
      "strIngredient3": "Bacon",
      "strIngredient4": "Challots",
      "strIngredient5": "Chestnut Mushroom",
      "strIngredient6": "Garlic Clove",
      "strIngredient7": "Bouquet Garni",
      "strIngredient8": "Tomato Puree",
      "strIngredient9": "Red Wine",
      "strIngredient10": "Celeriac",
      "strIngredient11": "Olive Oil",
      "strIngredient12": "Thyme",
      "strIngredient13": "Rosemary",
      "strIngredient14": "Bay Leaf",
      "strIngredient15": "Cardamom",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "3 tsp",
      "strMeasure2": "600g",
      "strMeasure3": "100g ",
      "strMeasure4": "350g",
      "strMeasure5": "250g",
      "strMeasure6": "2 sliced",
      "strMeasure7": "1",
      "strMeasure8": "1 tbs",
      "strMeasure9": "750 ml ",
      "strMeasure10": "600g",
      "strMeasure11": "2 tbs",
      "strMeasure12": "sprigs of fresh",
      "strMeasure13": "sprigs of fresh",
      "strMeasure14": "2",
      "strMeasure15": "4",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.bbcgoodfood.com/recipes/5032/beef-bourguignon",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ]
};

const mockDrinkData = 
{
  "drinks": [
    {
      "idDrink": "11007",
      "strDrink": "Margarita",
      "strDrinkAlternate": null,
      "strTags": "IBA,ContemporaryClassic",
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": "Contemporary Classics",
      "strAlcoholic": "Alcoholic",
      "strGlass": "Cocktail glass",
      "strInstructions": "Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.",
      "strInstructionsES": null,
      "strInstructionsDE": "Reiben Sie den Rand des Glases mit der Limettenscheibe, damit das Salz daran haftet. Achten Sie darauf, dass nur der äußere Rand angefeuchtet wird und streuen Sie das Salz darauf. Das Salz sollte sich auf den Lippen des Genießers befinden und niemals in den Cocktail einmischen. Die anderen Zutaten mit Eis schütteln und vorsichtig in das Glas geben.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Strofina il bordo del bicchiere con la fetta di lime per far aderire il sale.\r\nAvere cura di inumidire solo il bordo esterno e cospargere di sale.\r\nIl sale dovrebbe presentarsi alle labbra del bevitore e non mescolarsi mai al cocktail.\r\nShakerare gli altri ingredienti con ghiaccio, quindi versarli delicatamente nel bicchiere.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/5noda61589575158.jpg",
      "strIngredient1": "Tequila",
      "strIngredient2": "Triple sec",
      "strIngredient3": "Lime juice",
      "strIngredient4": "Salt",
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 1/2 oz ",
      "strMeasure2": "1/2 oz ",
      "strMeasure3": "1 oz ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": "https://commons.wikimedia.org/wiki/File:Klassiche_Margarita.jpg",
      "strImageAttribution": "Cocktailmarler",
      "strCreativeCommonsConfirmed": "Yes",
      "dateModified": "2015-08-18 14:42:59"
    }
  ]
};

const mockFoodRecommendations = {
  "meals": [
    {
      "idMeal": "52977",
      "strMeal": "Corba",
      "strDrinkAlternate": null,
      "strCategory": "Side",
      "strArea": "Turkish",
      "strInstructions": "Pick through your lentils for any foreign debris, rinse them 2 or 3 times, drain, and set aside.  Fair warning, this will probably turn your lentils into a solid block that you’ll have to break up later\r\nIn a large pot over medium-high heat, sauté the olive oil and the onion with a pinch of salt for about 3 minutes, then add the carrots and cook for another 3 minutes.\r\nAdd the tomato paste and stir it around for around 1 minute. Now add the cumin, paprika, mint, thyme, black pepper, and red pepper as quickly as you can and stir for 10 seconds to bloom the spices. Congratulate yourself on how amazing your house now smells.\r\nImmediately add the lentils, water, broth, and salt. Bring the soup to a (gentle) boil.\r\nAfter it has come to a boil, reduce heat to medium-low, cover the pot halfway, and cook for 15-20 minutes or until the lentils have fallen apart and the carrots are completely cooked.\r\nAfter the soup has cooked and the lentils are tender, blend the soup either in a blender or simply use a hand blender to reach the consistency you desire. Taste for seasoning and add more salt if necessary.\r\nServe with crushed-up crackers, torn up bread, or something else to add some extra thickness.  You could also use a traditional thickener (like cornstarch or flour), but I prefer to add crackers for some texture and saltiness.  Makes great leftovers, stays good in the fridge for about a week.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/58oia61564916529.jpg",
      "strTags": "Soup",
      "strYoutube": "https://www.youtube.com/watch?v=VVnZd8A84z4",
      "strIngredient1": "Lentils",
      "strIngredient2": "Onion",
      "strIngredient3": "Carrots",
      "strIngredient4": "Tomato Puree",
      "strIngredient5": "Cumin",
      "strIngredient6": "Paprika",
      "strIngredient7": "Mint",
      "strIngredient8": "Thyme",
      "strIngredient9": "Black Pepper",
      "strIngredient10": "Red Pepper Flakes",
      "strIngredient11": "Vegetable Stock",
      "strIngredient12": "Water",
      "strIngredient13": "Sea Salt",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "1 cup ",
      "strMeasure2": "1 large",
      "strMeasure3": "1 large",
      "strMeasure4": "1 tbs",
      "strMeasure5": "2 tsp",
      "strMeasure6": "1 tsp ",
      "strMeasure7": "1/2 tsp",
      "strMeasure8": "1/2 tsp",
      "strMeasure9": "1/4 tsp",
      "strMeasure10": "1/4 tsp",
      "strMeasure11": "4 cups ",
      "strMeasure12": "1 cup ",
      "strMeasure13": "Pinch",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://findingtimeforcooking.com/main-dishes/red-lentil-soup-corba/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53060",
      "strMeal": "Burek",
      "strDrinkAlternate": null,
      "strCategory": "Side",
      "strArea": "Croatian",
      "strInstructions": "Fry the finely chopped onions and minced meat in oil. Add the salt and pepper. Grease a round baking tray and put a layer of pastry in it. Cover with a thin layer of filling and cover this with another layer of filo pastry which must be well coated in oil. Put another layer of filling and cover with pastry. When you have five or six layers, cover with filo pastry, bake at 200ºC/392ºF for half an hour and cut in quarters and serve.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg",
      "strTags": "Streetfood, Onthego",
      "strYoutube": "https://www.youtube.com/watch?v=YsJXZwE5pdY",
      "strIngredient1": "Filo Pastry",
      "strIngredient2": "Minced Beef",
      "strIngredient3": "Onion",
      "strIngredient4": "Oil",
      "strIngredient5": "Salt",
      "strIngredient6": "Pepper",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "1 Packet",
      "strMeasure2": "150g",
      "strMeasure3": "150g",
      "strMeasure4": "40g",
      "strMeasure5": "Dash",
      "strMeasure6": "Dash",
      "strMeasure7": " ",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52978",
      "strMeal": "Kumpir",
      "strDrinkAlternate": null,
      "strCategory": "Side",
      "strArea": "Turkish",
      "strInstructions": "If you order kumpir in Turkey, the standard filling is first, lots of butter mashed into the potato, followed by cheese. There’s then a row of other toppings that you can just point at to your heart’s content – sweetcorn, olives, salami, coleslaw, Russian salad, allsorts – and you walk away with an over-stuffed potato because you got ever-excited by the choices on offer.\r\n\r\nGrate (roughly – you can use as much as you like) 150g of cheese.\r\nFinely chop one onion and one sweet red pepper.\r\nPut these ingredients into a large bowl with a good sprinkling of salt and pepper, chilli flakes (optional).",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/mlchx21564916997.jpg",
      "strTags": "SideDish",
      "strYoutube": "https://www.youtube.com/watch?v=IEDEtZ4UVtI",
      "strIngredient1": "Potatoes",
      "strIngredient2": "Butter",
      "strIngredient3": "Cheese",
      "strIngredient4": "Onion",
      "strIngredient5": "Red Pepper",
      "strIngredient6": "Red Chile Flakes",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2 large",
      "strMeasure2": "2 tbs",
      "strMeasure3": "150g",
      "strMeasure4": "1 large",
      "strMeasure5": "1 large",
      "strMeasure6": "Pinch",
      "strMeasure7": " ",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "http://www.turkeysforlife.com/2013/10/firinda-kumpir-turkish-street-food.html",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53026",
      "strMeal": "Tamiya",
      "strDrinkAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "Egyptian",
      "strInstructions": "oak the beans in water to cover overnight.Drain. If skinless beans are unavailable, rub to loosen the skins, then discard the skins. Pat the beans dry with a towel.\r\nGrind the beans in a food mill or meat grinder.If neither appliance is available, process them in a food processor but only until the beans form a paste. (If blended too smoothly, the batter tends to fall apart during cooking.) Add the scallions, garlic, cilantro, cumin, baking powder, cayenne, salt, pepper, and coriander, if using.  Refrigerate for at least 30 minutes.\r\nShape the bean mixture into 1-inch balls.Flatten slightly and coat with flour.\r\nHeat at least 1½-inches of oil over medium heat to 365 degrees.\r\nFry the patties in batches, turning once, until golden brown on all sides, about 5 minutes.Remove with a wire mesh skimmer or slotted spoon. Serve as part of a meze or in pita bread with tomato-cucumber salad and tahina sauce.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=mulqW-J3Yy4",
      "strIngredient1": "Broad Beans",
      "strIngredient2": "Spring Onions",
      "strIngredient3": "Garlic Clove",
      "strIngredient4": "Parsley",
      "strIngredient5": "Cumin",
      "strIngredient6": "Baking Powder",
      "strIngredient7": "Cayenne Pepper",
      "strIngredient8": "Flour",
      "strIngredient9": "Vegetable Oil",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "3 cups ",
      "strMeasure2": "6",
      "strMeasure3": "4",
      "strMeasure4": "1/4 cup",
      "strMeasure5": "2 tsp",
      "strMeasure6": "1 tsp ",
      "strMeasure7": "1/2 tsp",
      "strMeasure8": "Spinkling",
      "strMeasure9": "As required",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://oukosher.org/recipes/tamiya-egyptian-dried-fava-bean-fritters/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52785",
      "strMeal": "Dal fry",
      "strDrinkAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "Indian",
      "strInstructions": "Wash and soak toor dal in approx. 3 cups of water, for at least one hours. Dal will be double in volume after soaking. Drain the water.\r\nCook dal with 2-1/2 cups water and add salt, turmeric, on medium high heat, until soft in texture (approximately 30 mins) it should be like thick soup.\r\nIn a frying pan, heat the ghee. Add cumin seeds, and mustard seeds. After the seeds crack, add bay leaves, green chili, ginger and chili powder. Stir for a few seconds.\r\nAdd tomatoes, salt and sugar stir and cook until tomatoes are tender and mushy.\r\nAdd cilantro and garam masala cook for about one minute.\r\nPour the seasoning over dal mix it well and cook for another minute.\r\nServe with Naan.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg",
      "strTags": "Curry,Vegetarian,Cake",
      "strYoutube": "https://www.youtube.com/watch?v=J4D855Q9-jg",
      "strIngredient1": "Toor dal",
      "strIngredient2": "Water",
      "strIngredient3": "Salt",
      "strIngredient4": "Turmeric",
      "strIngredient5": "Ghee",
      "strIngredient6": "Chopped tomatoes",
      "strIngredient7": "Cumin seeds",
      "strIngredient8": "Mustard Seeds",
      "strIngredient9": "Bay Leaf",
      "strIngredient10": "Green Chili",
      "strIngredient11": "Ginger",
      "strIngredient12": "Cilantro",
      "strIngredient13": "Red Pepper",
      "strIngredient14": "Salt",
      "strIngredient15": "Sugar",
      "strIngredient16": "Garam Masala",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "1 cup",
      "strMeasure2": "2-1/2 cups",
      "strMeasure3": "1 tsp",
      "strMeasure4": "1/4 tsp",
      "strMeasure5": "3 tbs",
      "strMeasure6": "1 cup",
      "strMeasure7": "1/2 tsp",
      "strMeasure8": "1/2 tsp",
      "strMeasure9": "2",
      "strMeasure10": "1 tbs chopped",
      "strMeasure11": "2 tsp shredded",
      "strMeasure12": "2 tbs ",
      "strMeasure13": "1/2 tsp",
      "strMeasure14": "1/2 tsp",
      "strMeasure15": "1 tsp",
      "strMeasure16": "1/4 tsp",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.instagram.com/p/BO21bpYD3Fu",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52804",
      "strMeal": "Poutine",
      "strDrinkAlternate": null,
      "strCategory": "Miscellaneous",
      "strArea": "Canadian",
      "strInstructions": "Heat oil in a deep fryer or deep heavy skillet to 365°F (185°C).\r\nWarm gravy in saucepan or microwave.\r\nPlace the fries into the hot oil, and cook until light brown, about 5 minutes.\r\nRemove to a paper towel lined plate to drain.\r\nPlace the fries on a serving platter, and sprinkle the cheese over them.\r\nLadle gravy over the fries and cheese, and serve immediately.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/uuyrrx1487327597.jpg",
      "strTags": "UnHealthy,Speciality,HangoverFood",
      "strYoutube": "https://www.youtube.com/watch?v=UVAMAoA2_WU",
      "strIngredient1": "Vegetable Oil",
      "strIngredient2": "Beef Gravy",
      "strIngredient3": "Potatoes",
      "strIngredient4": "Cheese Curds",
      "strIngredient5": "",
      "strIngredient6": "",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "Dash",
      "strMeasure2": "1 Can",
      "strMeasure3": "5 thin cut",
      "strMeasure4": "2 cups",
      "strMeasure5": "",
      "strMeasure6": "",
      "strMeasure7": "",
      "strMeasure8": "",
      "strMeasure9": "",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "http://www.food.com/recipe/real-canadian-poutine-113388",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }]
  };

describe('Testa a página Recipe Details', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  it('Testa os componentes da Tela Recipe Details', async () => {
    const fetchMock = jest.spyOn(global, "fetch");
    global.fetch.mockResolvedValueOnce({
      json: jest.fn().mockResolvedValue(mockFoodData),
    });
    
    renderWithRouter(
      <RecipeDetails recipeType="food" match={ {params: { id: '52904' }} } />);

    expect(fetchMock).toBeCalledTimes(2);

    await waitForElementToBeRemoved(() => screen.queryByText(/loading/i));

    const recipeImage = screen.getByRole('img', {  name: /beef bourguignon/i})
    expect(recipeImage).toBeInTheDocument();

    const recipeName = screen.getByRole('heading', {  name: /beef bourguignon/i});
    expect(recipeName).toBeInTheDocument();

    const recipeCategory = screen.getByRole('heading', {  name: "Beef"});
    expect(recipeCategory).toBeInTheDocument();

    const ingredients = screen.getAllByTestId(/ingredient/i);
    expect(ingredients).toHaveLength(15);

    const instructions = screen.getByText('Heat a large casserole pan and add 1 tbsp goose fat.');
    expect(instructions).toBeInTheDocument();

    const video = screen.getByTestId('video');
    expect(video).toHaveAttribute('src', 'https://www.youtube.com/embed/SQnr4Z-7rok');
    expect(video).toBeInTheDocument();

    const recommendations = screen.getAllByTestId(/recomendation-card/i);
    expect(recommendations).toHaveLength(6);

    const startRecipeButton = screen.getByRole('button', { name: /start recipe/i })
    expect(startRecipeButton).toBeInTheDocument()
  });
});
